### ISSUE TITLE
"Reload" button is broken

### ISSUE THREAD

**Issue by tresf** [qzind/qz-print#130]
In the 2.0 branch, the reload button throws an `ArrayIndexOutOfBoundsException`.

Log attached.

```
[INFO] 2016-01-04 22:15:45,356 @ qz.ws.PrintSocketServer:?
        Shutting down server
[ERROR] 2016-01-04 22:15:45,372 @ qz.ws.PrintSocketServer:?
        Could not start tray manager
java.lang.ArrayIndexOutOfBoundsException: -1
        at qz.ws.PrintSocketServer.runServer(Unknown Source)
        at qz.ws.PrintSocketServer.main(Unknown Source)
[WARN] 2016-01-04 22:15:45,389 @ qz.ws.PrintSocketServer:?
        The web socket server is no longer running
```

**Comment by akberenz** [comment]
Fixed via 987ce73075e64ae7cb3b499379a208001db1248b
