### ISSUE TITLE
Invalid Vendor/Product ID throws NPE

### ISSUE THREAD

**Issue by tresf** [qzind/qz-print#134]
QZ Tray throws a NullPointerException when an invalid Vendor ID or invalid Product ID is specified.

Steps to reproduce:
1. Load sample.html
2. Click USB tab
3. Click List Devices
4. Pick a USB device by Vendor ID and Product ID
5. Fill in "Vendor ID" and "Product ID" with known-good values
6. Click "List Device Interfaces"
7. Observe correct functionality
8. Change "Vendor  ID" or "Product ID" to something invalid.
9. Click "List Device Interfaces"
10. NullPointerException is thrown.

```
[INFO] 2016-01-07 23:36:54,780 @ qz.common.TrayManager:421
    Allowed localhost to access USB devices
[ERROR] 2016-01-07 23:36:54,784 @ qz.ws.PrintSocketClient:199
    Problem processing message
java.lang.NullPointerException
    at qz.utils.UsbUtilities.getDeviceInterfaces(UsbUtilities.java:106)
    at qz.utils.UsbUtilities.getDeviceInterfacesJSON(UsbUtilities.java:112)
    at qz.ws.PrintSocketClient.processMessage(PrintSocketClient.java:297)
    at qz.ws.PrintSocketClient.onMessage(PrintSocketClient.java:192)
    at sun.reflect.GeneratedMethodAccessor10.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.eclipse.jetty.websocket.common.events.annotated.CallableMethod.call(CallableMethod.java:71)
    at org.eclipse.jetty.websocket.common.events.annotated.OptionalSessionCallableMethod.call(OptionalSessionCallableMethod.java:68)
    at org.eclipse.jetty.websocket.common.events.JettyAnnotatedEventDriver.onTextMessage(JettyAnnotatedEventDriver.java:209)
    at org.eclipse.jetty.websocket.common.message.SimpleTextMessage.messageComplete(SimpleTextMessage.java:69)
    at org.eclipse.jetty.websocket.common.events.AbstractEventDriver.appendMessage(AbstractEventDriver.java:64)
    at org.eclipse.jetty.websocket.common.events.JettyAnnotatedEventDriver.onTextFrame(JettyAnnotatedEventDriver.java:201)
    at org.eclipse.jetty.websocket.common.events.AbstractEventDriver.incomingFrame(AbstractEventDriver.java:160)
    at org.eclipse.jetty.websocket.common.WebSocketSession.incomingFrame(WebSocketSession.java:302)
    at org.eclipse.jetty.websocket.common.extensions.ExtensionStack.incomingFrame(ExtensionStack.java:214)
    at org.eclipse.jetty.websocket.common.Parser.notifyFrame(Parser.java:220)
    at org.eclipse.jetty.websocket.common.Parser.parse(Parser.java:258)
    at org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection.readParse(AbstractWebSocketConnection.java:613)
    at org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection.onFillable(AbstractWebSocketConnection.java:468)
    at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
    at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:610)
    at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:539)
    at java.lang.Thread.run(Thread.java:745)
```

**Comment by akberenz** [comment]
Closed with 05446a79ff24cea8ddbf6d486c578ec6a68a6165
