### ISSUE TITLE
qz-print 1.9.7 setRotation

### ISSUE THREAD

**Issue by klabarge** [qzind/qz-print#193]
Tested using the applet version 1.9.7

When using `setRotation` a NullPointerException is thrown.

**Code snippet**
```js
function printPDF() {
    if (notReady()) { return; }
    qz.setPaperSize("6.0in", "4.0in");
    qz.setRotation("90");
    qz.appendPDF(getPath() + "assets/pdf_sample.pdf");
    // Automatically gets called when "qz.appendPDF()" is finished.
    window['qzDoneAppending'] = function() {
        // Tell the applet to print PostScript.
        qz.printPS();

        // Remove reference to this function
        window['qzDoneAppending'] = null;
    };
}
```

**Stacktrace**
```
Nov 10, 2016 8:32:55 PM qz.PrintApplet call
INFO: Successfully called JavaScript function "qzDoneFinding(...)"...
Nov 10, 2016 8:32:55 PM qz.PrintApplet notifyBrowser
INFO: Successfully called JavaScript function "qzDoneFinding(...)"...
Nov 10, 2016 8:32:58 PM qz.PrintFunction setPaperSize
INFO: Set paper size to 6.0inx4.0in
Nov 10, 2016 8:32:58 PM qz.PrintApplet call
INFO: Successfully called JavaScript function "qzDoneAppending(...)"...
Nov 10, 2016 8:32:58 PM qz.PrintApplet notifyBrowser
INFO: Successfully called JavaScript function "qzDoneAppending(...)"...
Nov 10, 2016 8:32:58 PM qz.PrintFunction logCommands
INFO: 

    <<http://localhost/qz-print-1.9/demo/assets/pdf_sample.pdf>>


Nov 10, 2016 8:32:58 PM qz.common.LogIt log
INFO: Rotating image 1.5707963267948966
Nov 10, 2016 8:32:58 PM qz.common.LogIt log
SEVERE: Error
java.lang.NullPointerException
	at qz.PrintPostScript.rotate(Unknown Source)
	at qz.PrintPostScript.print(Unknown Source)
	at qz.PrintFunction.logAndPrint(Unknown Source)
	at qz.PrintFunction.printPS(Unknown Source)
	at qz.PrintApplet.startJavaScriptListener(Unknown Source)
	at qz.PrintApplet.access$000(Unknown Source)
	at qz.PrintApplet$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at qz.PrintApplet.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

java.lang.NullPointerException
	at qz.PrintPostScript.rotate(Unknown Source)
	at qz.PrintPostScript.print(Unknown Source)
	at qz.PrintFunction.logAndPrint(Unknown Source)
	at qz.PrintFunction.printPS(Unknown Source)
	at qz.PrintApplet.startJavaScriptListener(Unknown Source)
	at qz.PrintApplet.access$000(Unknown Source)
	at qz.PrintApplet$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at qz.PrintApplet.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Nov 10, 2016 8:32:58 PM qz.PrintRaw clear
INFO: Print buffer has been cleared.
Nov 10, 2016 8:32:58 PM qz.PrintApplet call
INFO: Successfully called JavaScript function "qzDonePrinting(...)"...
Nov 10, 2016 8:32:58 PM qz.PrintApplet notifyBrowser
INFO: Successfully called JavaScript function "qzDonePrinting(...)"...
```

**Comment by tresf** [comment]
Confirmed however PDFRenderer doesn't offer an easy way to honor PDF rotation, so we'll have to close this as `wontfix`.

The recommended workaround is to use landscape via:

``` js
qz.setPaperSize("4in", "6in")
qz.setOrientation("landscape");
```

![image](https://cloud.githubusercontent.com/assets/6345473/20204218/cf03c4f6-a79b-11e6-85c7-8ee1bb17b2ad.png)

**Comment by tresf** [comment]
Closing as `wontfix`.  Please use `landscape` orientation instead.
