### ISSUE TITLE
Applet:  NoClassDefFoundError, pdfrenderer/jssc

### ISSUE THREAD

**Issue by tresf** [qzind/qz-print#30]
Running through some final testing and having a problem with the applet deployment when using PDF or Serial functionality.  It appears the library/JAR isn't being found by the applet.

Probably a resurfacing of #9 as the symptom is identical.  This time, we can reproduce.   Just run sample.html from `out\dist\applet\demo` and try either the PDF for Serial options.

```
Exception in thread "Thread-17" java.lang.NoClassDefFoundError: com/sun/pdfview/PDFFile
    at qz.PrintPostScript.getPDFFile(Unknown Source)
    at qz.PrintPostScript.print(Unknown Source)
    at qz.PrintFunction.logAndPrint(Unknown Source)
    at qz.PrintFunction.printPS(Unknown Source)
    at qz.PrintApplet.startJavaScriptListener(Unknown Source)
    at qz.PrintApplet.access$000(Unknown Source)
    at qz.PrintApplet$1.run(Unknown Source)
    at java.security.AccessController.doPrivileged(Native Method)
    at qz.PrintApplet.run(Unknown Source)
    at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ClassNotFoundException: com.sun.pdfview.PDFFile
    at sun.plugin2.applet.Plugin2ClassLoader$2.run(Unknown Source)
    at sun.plugin2.applet.Plugin2ClassLoader$2.run(Unknown Source)
    at java.security.AccessController.doPrivileged(Native Method)
    at sun.plugin2.applet.Plugin2ClassLoader.findClassHelper(Unknown Source)
    at sun.plugin2.applet.JNLP2ClassLoader.findClass(Unknown Source)
    at sun.plugin2.applet.Plugin2ClassLoader.loadClass0(Unknown Source)
    at sun.plugin2.applet.Plugin2ClassLoader.loadClass(Unknown Source)
    at sun.plugin2.applet.Plugin2ClassLoader.loadClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    ... 10 more
```

Tagging @robertcasto @bberenz

**Comment by tresf** [comment]
Ok, the `NoClassDefFoundError` is resolved per 6385179, but these libraries aren't signed, so we're getting a mixed content warning now. @robertcasto, for the applet to work properly, all Jars on the classpath must also be signed.

![image](https://cloud.githubusercontent.com/assets/6345473/7907051/44485096-0802-11e5-8abd-68d6760ed9e4.png)

**Comment by robertcasto** [comment]
Got it. I'll make sure Brett gets it signed. Thanks!

On Mon, Jun 1, 2015 at 2:03 AM, Tres Finocchiaro notifications@github.com
wrote:

> Ok, the NoClassDefFoundError is resolved per 6385179
> https://github.com/qzind/qz-print/commit/6385179769667d104ef62801f252a9aebfcd814b,
> but these libraries aren't signed, so we're getting a mixed content warning
> now. @robertcasto https://github.com/robertcasto, for the applet to
> work properly, all Jars on the classpath must also be signed.
> 
> [image: image]
> https://cloud.githubusercontent.com/assets/6345473/7907051/44485096-0802-11e5-8abd-68d6760ed9e4.png
> 
> ## 
> 
> Reply to this email directly or view it on GitHub
> https://github.com/qzind/qz-print/issues/30#issuecomment-107318937.

## 

_[image: SellersToolbox Website] http://www.sellerstoolbox.com_  Robert
Casto
_(owner)_
Tools for Amazon Sellers
p: 1-513-847-4942
c: 1-513-886-1550
e: casto.robert@gmail.com

**Comment by akberenz** [comment]
Should be taken care of via 07e91c49ea8dcff5d7b7606e00bda685de2f59ed

**Comment by tresf** [comment]
@bberenz does this also address the `tsaurl` signing method (trusted) ?

**Comment by akberenz** [comment]
.. it does now

**Comment by tresf** [comment]
> .. it does now

:+1:

**Comment by tresf** [comment]
Thanks.  Closing.  I'll reopen if I have any issues.
