### ISSUE TITLE
qz.findPrinter() not working

### ISSUE THREAD

**Issue by tresf** [qzind/qz-print#96]
In 1.8 (applet), `qz.findPrinter()` was a [completely valid command](https://code.google.com/p/jzebra/wiki/TutorialWebApplet#Printing).  Now with 1.9, it is not.

The exact error message is:

```
Sep 1, 2015 12:00:00 AM qz.PrintApplet run
INFO: ===== JAVASCRIPT LISTENER THREAD STOPPED =====
Exception in thread "Thread-16" java.lang.NullPointerException
    at qz.PrintApplet.startJavaScriptListener(Unknown Source)
    at qz.PrintApplet.access$000(Unknown Source)
    at qz.PrintApplet$1.run(Unknown Source)
    at java.security.AccessController.doPrivileged(Native Method)
    at qz.PrintApplet.run(Unknown Source)
    at java.lang.Thread.run(Thread.java:745)
cache: Clean up the reference queue: file:/Users/foo/bar/qz-print.jar
```

**Comment by tresf** [comment]
Partially caused with the introduction of #86, as dummy printer logic was doing string comparison against null causing NPE.  Closed via bbf0263, checks for null prior to comparing string.

![image](https://cloud.githubusercontent.com/assets/6345473/10154121/8affe9d0-6631-11e5-97a4-98a8155c16b4.png)
